BULK INSERT passenger_feedback
FROM 'D:\VERTOCITY INTEGRATED DATASCIENCE FILES\DATA SCIENCE END-TO-END CASPTONE PROJECTS\DATA-SCIENCE END-TO-END CASPTONE 1 PROJECT\Trasnport SQL CSV FILE\transportSystem.csv'
WITH
(
    FIELDTERMINATOR = ',', 
    ROWTERMINATOR = '\n',
    FIRSTROW = 2
);
